//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beedget
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int BudgetID { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> TargetAmount { get; set; }
        public decimal CurrentAmount { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public int isAchieved { get; set; }
        public int UserID { get; set; }
        public int BudgetTypeID { get; set; }
    
        public virtual BudgetType BudgetType { get; set; }
        public virtual Users Users { get; set; }
    }
}
