//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beedget
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseType
    {
        public int ExpenseID { get; set; }
        public int CategoryID { get; set; }
        public int UserID { get; set; }
        public string ExpenseName { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
    }
}
