//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beedget
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeedgetDBEntities : DbContext
    {
        public BeedgetDBEntities()
            : base("name=BeedgetDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Checklist> Checklist { get; set; }
        public DbSet<ExpenseType> ExpenseType { get; set; }
        public DbSet<SavingsType> SavingsType { get; set; }
        public DbSet<User> User { get; set; }
    }
}
