//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beedget
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavingsType
    {
        public int SavingsID { get; set; }
        public int UserID { get; set; }
        public string SavingsName { get; set; }
        public string CategoryName { get; set; }
        public decimal TargetAmount { get; set; }
        public decimal CurrentAmount { get; set; }
        public System.DateTime TargetDate { get; set; }
        public string AddNotes { get; set; }
    }
}
